# Generated by Django 4.2.1 on 2023-07-07 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='vendor',
        ),
    ]
